<?php

namespace ContainerCjo40T4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__JCTJ2yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..JCTJ2y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..JCTJ2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'server' => ['privates', '.errored..service_locator..JCTJ2y.App\\Entity\\Server', NULL, 'Cannot autowire service ".service_locator..JCTJ2y": it needs an instance of "App\\Entity\\Server" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'server' => 'App\\Entity\\Server',
        ]);
    }
}
