<?php

namespace ContainerCjo40T4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CWcNGgcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CWcNGgc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CWcNGgc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serverRepository' => ['privates', 'App\\Repository\\ServerRepository', 'getServerRepositoryService', true],
        ], [
            'serverRepository' => 'App\\Repository\\ServerRepository',
        ]);
    }
}
