<?php

namespace ContainerCjo40T4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'EasyCorp\Bundle\EasyAdminBundle\Factory\FieldFactory' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Factory\FieldFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Factory/FieldFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Factory/FormLayoutFactory.php';

        $instance = new \EasyCorp\Bundle\EasyAdminBundle\Factory\FieldFactory(($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Provider\\AdminContextProvider'] ?? self::getAdminContextProviderService($container)), ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Security\\AuthorizationChecker'] ?? self::getAuthorizationCheckerService($container)), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\CommonPreConfigurator'] ?? $container->load('getCommonPreConfiguratorService'));
            yield 1 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\ArrayConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\ArrayConfigurator());
            yield 2 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\AssociationConfigurator'] ?? $container->load('getAssociationConfiguratorService'));
            yield 3 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\AvatarConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\AvatarConfigurator());
            yield 4 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\BooleanConfigurator'] ?? $container->load('getBooleanConfiguratorService'));
            yield 5 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\CollectionConfigurator'] ?? $container->load('getCollectionConfiguratorService'));
            yield 6 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\CountryConfigurator'] ?? $container->load('getCountryConfiguratorService'));
            yield 7 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\CurrencyConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\CurrencyConfigurator());
            yield 8 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\DateTimeConfigurator'] ?? $container->load('getDateTimeConfiguratorService'));
            yield 9 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\EmailConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\EmailConfigurator());
            yield 10 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\FormConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\FormConfigurator());
            yield 11 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\IdConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\IdConfigurator());
            yield 12 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\ImageConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\ImageConfigurator(\dirname(__DIR__, 4)));
            yield 13 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\IntegerConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\IntegerConfigurator());
            yield 14 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\LanguageConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\LanguageConfigurator());
            yield 15 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\LocaleConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\LocaleConfigurator());
            yield 16 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\MoneyConfigurator'] ?? $container->load('getMoneyConfiguratorService'));
            yield 17 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\NumberConfigurator'] ?? $container->load('getNumberConfiguratorService'));
            yield 18 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\PercentConfigurator'] ?? $container->load('getPercentConfiguratorService'));
            yield 19 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\ChoiceConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\ChoiceConfigurator());
            yield 20 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\SlugConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\SlugConfigurator());
            yield 21 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\TelephoneConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\TelephoneConfigurator());
            yield 22 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\TextConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\TextConfigurator());
            yield 23 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\TimezoneConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\TimezoneConfigurator());
            yield 24 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\UrlConfigurator'] ??= new \EasyCorp\Bundle\EasyAdminBundle\Field\Configurator\UrlConfigurator());
            yield 25 => ($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Field\\Configurator\\CommonPostConfigurator'] ?? $container->load('getCommonPostConfiguratorService'));
        }, 26), new \EasyCorp\Bundle\EasyAdminBundle\Factory\FormLayoutFactory(($container->services['translator'] ?? self::getTranslatorService($container))));

        if (isset($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Factory\\FieldFactory'])) {
            return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Factory\\FieldFactory'];
        }

        return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Factory\\FieldFactory'] = $instance;
    }
}
