<?php

namespace ContainerCjo40T4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..JCTJ2y.App\Entity\Server' shared service.
     *
     * @return \App\Entity\Server
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..JCTJ2y": it needs an instance of "App\\Entity\\Server" but this type has been excluded in "config/services.yaml".');
    }
}
