<?php

namespace ContainerCjo40T4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkinCrudControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\SkinCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\SkinCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/SkinCrudController.php';

        $instance = new \App\Controller\Admin\SkinCrudController();

        if (isset($container->services['App\\Controller\\Admin\\SkinCrudController'])) {
            return $container->services['App\\Controller\\Admin\\SkinCrudController'];
        }

        $container->services['App\\Controller\\Admin\\SkinCrudController'] = $instance;

        $instance->setContainer(($container->privates['.service_locator.fodCAGo'] ?? $container->load('get_ServiceLocator_FodCAGoService'))->withContext('App\\Controller\\Admin\\SkinCrudController', $container));

        return $instance;
    }
}
