<?php

namespace ContainerVkxToZm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1xOTAnJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1xOTAnJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1xOTAnJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'server' => ['privates', '.errored..service_locator.1xOTAnJ.App\\Entity\\Server', NULL, 'Cannot autowire service ".service_locator.1xOTAnJ": it needs an instance of "App\\Entity\\Server" but this type has been excluded in "config/services.yaml".'],
        ], [
            'server' => 'App\\Entity\\Server',
        ]);
    }
}
