<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVkxToZm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVkxToZm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVkxToZm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVkxToZm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVkxToZm\App_KernelDevDebugContainer([
    'container.build_hash' => 'VkxToZm',
    'container.build_id' => '85a0f1b6',
    'container.build_time' => 1768307993,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVkxToZm');
